<div class="row">
	<div class="row">
		<div class="col-md-9">
			<nav class="navbar navbar-default" role="navigation">
				<div class="container ">
					<a href="">DASHBOARD</a>
					<a href="">EVENTS</a>
					<a href="">SETTINGS</a>
				</div>
			</nav>
			<div><spine::calendar/></div>
		</div>
		<div class="col-md-3">
			<div class="row">
				<div class="panel panel-default">
					<div class="panel-heading "></div>
					<div class="panel-body">
						<b>Username: </b><br/>
						<span><?=$username?></span><br/>
						<b>Full Name: </b><br/>
						<span><?=ucwords($first_name)." ".ucwords($last_name)?></span><br/>
						<b>Email Address: </b><br/>
						<span><?=$email_address?></span><br/>
						<b>Contact Number: </b><br/>
						<span><?=$contact_number?></span><br/>
						<b>Home Address: </b><br/>
						<span><?=$home_address?></span><br/>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>