<div class="spT-4"></div>
<form role="form" lass="form-horizontal" method="POST">
	<div class="form-group">
		<label for="username_txt">Username</label>
		<input type="username" class="form-control" id="username_txt" placeholder="Enter Username" name="username">
	</div>
	<div class="form-group">
		<label for="password_txt">Password</label>
		<input type="password" class="form-control" id="password_txt" placeholder="Password" name="password">
	</div>
	<button type="submit" class="btn btn-default" name="login">Submit</button>
</form>
<div class="spB-4"></div>
