<div class="page-header">
	<h1>User Registration</h1>
</div>
<form role="form" lass="form-horizontal" method="POST">
	<div class="form-group">
		<label for="Role">Role</label>
		<select class="form-control" name="role">
			<option value="2">Administrator</option>
			<option value="3">Counselor</option>
		</select>
	</div>
	<div class="form-group">
		<label for="username">Username</label>
		<input type="text" class="form-control" id="username" placeholder="Enter Username" name="username">
	</div>
	<div class="form-group">
		<label for="password">Password</label>
		<input type="password" class="form-control" id="password" placeholder="Password" name="password">
	</div>
	<div class="form-group">
		<label for="first_name">First Name</label>
		<input type="text" class="form-control" id="first_name" placeholder="First Name" name="first_name">
	</div>
	<div class="form-group">
		<label for="last_name">Last Name</label>
		<input type="text" class="form-control" id="last_name" placeholder="Last Name" name="last_name">
	</div>
	<div class="form-group">
		<label for="contact_number">Contact Number</label>
		<input type="text" class="form-control" id="contact_number" placeholder="Contact Number(s) comma separated" name="contact_number">
	</div>
	<div class="form-group">
		<label for="first_name">Email Address</label>
		<input type="text" class="form-control" id="email_address" placeholder="Email Address" name="email_address">
	</div>
	<div class="form-group">
		<label for="home_address">Home Address</label>
		<input type="text" class="form-control" id="home_address" placeholder="Home Address" name="home_address">
	</div>
	<button type="submit" class="btn btn-default" name="register">Register</button>
	<button type="reset" class="btn btn-default">Reset</button>
</form>
